name: Module 2 Exercise
on: push
jobs:
  lint-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  #test-run:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Get Code
  #      r
  #deploy:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy run
  #      run: echo "Running deployment"
